const characterData = [
    { src: "asset/character/angry.png", name: "화난 범뮤" },
    { src: "asset/character/cowboy.png", name: "카우보이 범뮤" },
    { src: "asset/character/cyborg.png", name: "사이보그 범뮤" },
    { src: "asset/character/hanbok.png", name: "한복 범뮤" },
    { src: "asset/character/idol.png", name: "아이돌 범뮤" },
    { src: "asset/character/knight.png", name: "기사 범뮤" },
    { src: "asset/character/normal.png", name: "평범한 범뮤" },
    { src: "asset/character/prince.png", name: "왕자 범뮤" },
    { src: "asset/character/princess.png", name: "공주 범뮤" },
    { src: "asset/character/student.png", name: "학생 범뮤" },
    { src: "asset/character/summer.png", name: "여름 범뮤" },
    { src: "asset/character/demon.png", name: "마왕 범뮤" },
    { src: "asset/character/bikini.png", name: "비키니 범뮤" },
    { src: "asset/character/snowman.png", name: "눈사람 범뮤" },
];
